# Shell variables
# Generated by 'wal'
wallpaper='/home/diaz/.config/wpg/wallpapers/street.jpg'

# Special
background='#0c1412'
foreground='#c1a99f'
cursor='#c1a99f'

# Colors
color0='#0c1412'
color1='#273C43'
color2='#4F3C45'
color3='#12515A'
color4='#35494B'
color5='#4B504C'
color6='#686056'
color7='#c1a99f'
color8='#87766f'
color9='#273C43'
color10='#4F3C45'
color11='#12515A'
color12='#35494B'
color13='#4B504C'
color14='#686056'
color15='#c1a99f'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
