--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/diaz/.config/wpg/wallpapers/street.jpg"

-- Special
background="#0c1412"
foreground="#c1a99f"
cursor="#c1a99f"

-- Colors
color0="#0c1412"
color1="#273C43"
color2="#4F3C45"
color3="#12515A"
color4="#35494B"
color5="#4B504C"
color6="#686056"
color7="#c1a99f"
color8="#87766f"
color9="#273C43"
color10="#4F3C45"
color11="#12515A"
color12="#35494B"
color13="#4B504C"
color14="#686056"
color15="#c1a99f"
